// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: edyxerhefzsqnsoqrvts

class SupabaseConfig {
  static const String supabaseUrl = 'https://edyxerhefzsqnsoqrvts.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkeXhlcmhlZnpzcW5zb3FydnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5OTk0NTksImV4cCI6MjA4NDU3NTQ1OX0.r5Movee54ZDX_8TMvEc_7DQGfQIek254ivfE6pPxowA';
}
